### ISSUE TITLE
Posibilă integrare cu romania-choropleth?

### ISSUE THREAD

**Issue by cimi** [funkycitizens/onoratainstanta#1]
Salut!

Uitându-mă puțin peste proiect, am văzut că încercați să faceți ceva similar cu ce am făcut eu cu [romania-choropleth](https://github.com/cimi/romania-choropleth). 

Pe scurt, e făcut peste d3.js, primește o configurare - care acum mi se pare destul de complexă pentru gustul meu - și desenează o hartă a româniei care se colorează automat în funcție de datele de intrare.

Eu nu m-am atins de proiect de vreo 3 ani și nu știu nicăieri altundeva unde să fie folosit cu excepția paginii de demo, dar ar trebui să fie OK dacă aveți nevoie de randat o hartă a României pe județe cu topojson. M-aș bucura să vă fie util, dacă vreți să o încercați și găsiți probleme sau aveți nevoie de feature-uri care nu sunt suportate puteți să creați issue-uri în repo-ul proiectului și o să încerc să vă ajut.

Spor!
Alex

**Comment by mgax** [comment]
Wow, văd că ai muncit ceva la romania-choropleth. Noi o să avem nevoie și de alte geometrii (curțile de apel, de exemplu, deservesc mai multe județe) și oricum, pentru ce vrem să afișăm, partea cu harta n-a fost complicată, deci cred că o să păstrăm codul custom. Dar merci de info! :)
